### ISSUE TITLE
Implement cool down for motion notifications

### ISSUE THREAD

**Issue by eliseomartelli** [eliseomartelli/ParentsHomeAutomation#7]
Implement cool down for motion notification using the new run mode that will be introduced in Home Assistant 0.113.

## Example:

```yaml
automation:
  - alias: "Doorbell cool down"
    description: "Prevent multiple message being send when spamming the doorbell."
    mode: single # Which is the default
    trigger:
      - platform: state
        state: binary_sensor.doorbell
        to: "on"
    action:
      - service: notify.frenck
        data:
          message: Ding dong! Someone is at the door!
      - delay:
          seconds: 10
```
