### ISSUE TITLE
Add DB purging at a fixed time interval

### ISSUE THREAD

**Issue by eliseomartelli** [eliseomartelli/ParentsHomeAutomation#8]
Configure the recorder integration to purge the database every 7 days to keep the DB from taking a lot of space. 
Tweak the commit interval to lower the times home assistant writes to disk.

https://www.home-assistant.io/integrations/recorder/

## Example:

```yaml
recorder:
  auto_purge: true
  purge_keep_days: 7
  commit_interval: 10 
```
